name: build and publish

on:
  push:
      branches:
        - master

jobs:
  build:
    name: Docker Image
    runs-on: ubuntu-latest
    needs: test
    env:
      GITHUB_PACKAGE: docker.pkg.github.com/raphapr/linuxkit-docker/linuxkit
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CI_SSH_KEY }}
      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build . \
          --ssh default \
          --progress=plain \
          --tag linuxkit:${{ github.sha }}
      - name: Tag for Github Packages
        run: docker tag linuxkit:${{ github.sha }} $GITHUB_PACKAGE:${{ github.sha }}
      - name: Docker Login Github
        run: docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Publish Docker image Github
        run: docker push $GITHUB_PACKAGE:${{ github.sha }}
